// lib/codegen.ts
import type { LandingPageBlueprint } from "@/types";

function esc(text: string): string {
  return text.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Serializes a LandingPageBlueprint into a single, copy-paste-ready
 * React + Tailwind CSS component file (no external UI library dependency).
 */
export function generateComponentCode(blueprint: LandingPageBlueprint): string {
  const { meta, hero, featureGrid, pricing, cta } = blueprint;

  return `import { ${Array.from(
    new Set(featureGrid.features.map((f) => f.icon))
  ).join(", ")}, Check, ArrowRight } from "lucide-react";

// Generated by PageCraft AI for "${esc(meta.productName)}"
// Paste into any Next.js / React + Tailwind project.

export default function ${meta.productName.replace(/[^a-zA-Z0-9]/g, "") || "LandingPage"}() {
  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-100">
      {/* Hero */}
      <section className="mx-auto max-w-5xl px-6 pt-28 pb-20 text-center">
        <span className="inline-block rounded-full border border-zinc-800 px-4 py-1 text-sm text-zinc-400">
          ${esc(hero.eyebrow)}
        </span>
        <h1 className="mt-6 text-4xl md:text-6xl font-semibold tracking-tight">
          ${esc(hero.headline)}
        </h1>
        <p className="mt-6 text-lg text-zinc-400 max-w-2xl mx-auto">
          ${esc(hero.subheadline)}
        </p>
        <div className="mt-10 flex items-center justify-center gap-4">
          <button className="rounded-lg bg-white text-zinc-950 px-6 py-3 font-medium hover:bg-zinc-200 transition-colors">
            ${esc(hero.primaryCta)}
          </button>
          <button className="rounded-lg border border-zinc-700 px-6 py-3 font-medium hover:bg-zinc-900 transition-colors">
            ${esc(hero.secondaryCta)}
          </button>
        </div>
      </section>

      {/* Feature Grid */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="text-center max-w-2xl mx-auto">
          <h2 className="text-3xl font-semibold">${esc(featureGrid.heading)}</h2>
          <p className="mt-4 text-zinc-400">${esc(featureGrid.subheading)}</p>
        </div>
        <div className="mt-14 grid grid-cols-1 md:grid-cols-3 gap-6">
${featureGrid.features
  .map(
    (f) => `          <div className="rounded-xl border border-zinc-800 p-6">
            <${f.icon} className="h-6 w-6 text-zinc-300" />
            <h3 className="mt-4 font-medium">${esc(f.title)}</h3>
            <p className="mt-2 text-sm text-zinc-400">${esc(f.description)}</p>
          </div>`
  )
  .join("\n")}
        </div>
      </section>

      {/* Pricing */}
      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="text-center max-w-2xl mx-auto">
          <h2 className="text-3xl font-semibold">${esc(pricing.heading)}</h2>
          <p className="mt-4 text-zinc-400">${esc(pricing.subheading)}</p>
        </div>
        <div className="mt-14 grid grid-cols-1 md:grid-cols-${pricing.tiers.length} gap-6">
${pricing.tiers
  .map(
    (t) => `          <div className="rounded-xl border ${
      t.highlighted ? "border-white" : "border-zinc-800"
    } p-8">
            <h3 className="font-medium">${esc(t.name)}</h3>
            <p className="mt-4 text-3xl font-semibold">${esc(t.price)}<span className="text-base font-normal text-zinc-400">/${esc(
      t.billingPeriod
    )}</span></p>
            <p className="mt-2 text-sm text-zinc-400">${esc(t.description)}</p>
            <ul className="mt-6 space-y-3 text-sm">
${t.features
  .map(
    (feat) => `              <li className="flex items-center gap-2">
                <Check className="h-4 w-4 text-zinc-400" />
                ${esc(feat)}
              </li>`
  )
  .join("\n")}
            </ul>
            <button className="mt-8 w-full rounded-lg ${
              t.highlighted
                ? "bg-white text-zinc-950 hover:bg-zinc-200"
                : "border border-zinc-700 hover:bg-zinc-900"
            } px-6 py-3 font-medium transition-colors">
              ${esc(t.ctaLabel)}
            </button>
          </div>`
  )
  .join("\n")}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-4xl px-6 py-24 text-center">
        <h2 className="text-3xl md:text-4xl font-semibold">${esc(cta.headline)}</h2>
        <p className="mt-4 text-zinc-400">${esc(cta.subheadline)}</p>
        <button className="mt-8 inline-flex items-center gap-2 rounded-lg bg-white text-zinc-950 px-6 py-3 font-medium hover:bg-zinc-200 transition-colors">
          ${esc(cta.buttonLabel)}
          <ArrowRight className="h-4 w-4" />
        </button>
      </section>
    </main>
  );
}
`;
}
